apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nginx.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    environment: {{ .Values.metadata.environment }}
spec:
  selector:
    app: {{ .Values.metadata.labels.app }} 
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.port | default 80 }}         
      targetPort: {{ .Values.nginx.port | default 80 }}  
  type: ClusterIP 

