apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.exporter.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    environment: {{ .Values.metadata.environment }}
spec:
  selector:
    app: {{ .Values.metadata.labels.app }} 
  ports:
    - protocol: TCP
      port: {{ .Values.exporter.port }}         
      targetPort: {{ .Values.exporter.port }}  
  type: ClusterIP  

