metadata:
  name: "smev-proxy-deployment"
  labels:
    app: "smev-proxy"
    environment: "devops-utils"

replicaCount: 2


nginx:
  image:
    repository: "nexus.exportcenter.ru/docker/docker-base-images/nginx/nginx-alpine:1.26.2"  
    tag: "1.26.2" 
    pullPolicy: "Always"  
  port: 8080 
  listenPort: 8080  
  statusPort: 8080 
  workerProcesses: "auto"  
  workerConnections: 1024  
  externalServers:
    - "http://smev3-n0.test.gosuslugi.ru:7500/smev/v1.1/ws"
  loadBalancingAlgorithm: "least_conn"  
  statusAccess:
    allow: "10.5.0.0/16"  
  resources:
    requests:
      cpu: "200m"  
      memory: "256Mi"  
    limits:
      cpu: "500m"  
      memory: "512Mi"  
  config:
    volumeName: "nginx-config-volume"  
    mountPath: "/etc/nginx"  
    subPath: "nginx.conf"  
    configMapName: "nginx-config-map"  



exporter:
  image:
    repository: "nexus.exportcenter.ru/docker/docker-base-images/nginx-prometheus-exporter/nginx-exporter:1.3.0"  
    tag: "1.3.0" 
    pullPolicy: "Always"  
  port: 9113  
  scrapeInterval: "15s" 
  statusUrl: "http://localhost:8080/nginx_status" 
  access:
    allow: "10.5.0.0/16"  
  resources:
    requests:
      cpu: "100m"  
      memory: "128Mi" 
    limits:
      cpu: "200m"  
      memory: "256Mi"  
  config:
    volumeName: "nginx-exporter-config-volume" 
    mountPath: "/etc/nginx-exporter"  
    subPath: "nginx-exporter.conf"  
    configMapName: "nginx-exporter-config-map" 


services:
  nginx:
    name: "nginx-service" 
    type: "ClusterIP"  
    port: 8080  
    targetPort: 8080  
  exporter:
    name: "nginx-exporter-service"  
    type: "ClusterIP"  
    port: 8081 
    targetPort: 8080  


configMaps:
  nginx:
    name: "nginx-config-map" 
  exporter:
    name: "nginx-exporter-config-map"  


DeploymentUpdate:
  maxSurge: "1"  
  maxUnavailable: "1"  

# Настройки livenessProbe и readinessProbe
livenessProbe:
  nginx:
    path: "/smev-proxy/api/v1/status" 
    initialDelaySeconds: 30  
    periodSeconds: 10  
  exporter:
    path: "/smev-proxy/api/v1/status"
    initialDelaySeconds: 30  
    periodSeconds: 10 

readinessProbe:
  nginx:
    path: "/smev-proxy/api/v1/status"
    initialDelaySeconds: 10  
    periodSeconds: 5  
  exporter:
    path: "/smev-proxy/api/v1/status"
    initialDelaySeconds: 10  
    periodSeconds: 5  


















